url: "jdbc:mysql://localhost:3306/test"
user: "root"
password: "root"
currencies:
language:
  default: ru
  ru:
    PlayerBalance:
        another_player: "Баланс игрока по данной валюте:"
        you: "Ваш баланс по данной валюте:"
    CurCheckExeption: "Введенная вами валюта не существует!"
    PlayerIsNotOnline: "Игрок не онлайн!"
    CurList: "Список валют:"
    Use: "Используйте:"

